server:
  port: ${PORT:8090}

# API URL : http://localhost:8090/swagger-ui/index.html
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC